#ifndef FOO_DANMAKU_H
#define FOO_DANMAKU_H

#include <foobar2000/SDK/foobar2000.h>

#define MY_COMPONENT_NAME "FooBar Danmaku"
#define MY_COMPONENT_VERSION_MAJOR 2
#define MY_COMPONENT_VERSION_MINOR 1
#define MY_COMPONENT_VERSION_BUILD 0
#define MY_COMPONENT_VERSION (MY_COMPONENT_VERSION_MAJOR << 16 | MY_COMPONENT_VERSION_MINOR << 8 | MY_COMPONENT_VERSION_BUILD)

extern DWORD g_danmaku_hotkey;

#endif // FOO_DANMAKU_H